### PR TITLE
make sure to use briefcase 0.2

### PR DESCRIPTION
**Pull request by jessa0**
briefcase 0.3 is a big breaking change

### CODE REVIEW

**Review by nolanl — APPROVED** [review]
Looks good. Tests are failing, but that looks like it is due to a change in how ttys are allocated in github actions, not this change.

**Comment by nolanl** [comment]
Oddly, the linux test build seems to still pull in 0.3?

**Comment by jessa0** [comment]
> Oddly, the linux test build seems to still pull in 0.3?

fixed. i grepped, and there were a bunch of other un-fixed briefcase installs in other build files.

**Comment by jessa0** [comment]
unfortunately, i can't test the changes to the Vagrantfile, as i can't get the the macos/windows provisioners to work for unrelated reasons.

**Comment by jessa0** [comment]
I fixed the windows provisioner (which I'll submit in a separate PR) and this PR successfully builds in the windows VM. still cannot get macos VM to run.

**Pull request merged**
